#include "ESP8266WiFi.h"
#include "ESP8266WebServer.h"
#define TXD 1 // GPIO1/TXD01

ESP8266WebServer server(80);
const char* ssid = "RT-GPON-F178";
const char* password =  "F3bf2g6d97";
byte tries = 10;  // Попыткок подключения к точке доступа

const char * htmlMessage = " <!DOCTYPE html> "
                           "<html lang=\"ru\"> "
                           "<head>"
                           "<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">"
                           "<title>Smart Тепло</title>"
                           "</head>"
                           "<body>"
                           "<header class=\"header\">"
                           "<a href=\"#\" class=\"logo\">Smart Тепло</a>"
                           "<input class=\"side-menu\" type=\"checkbox\" id=\"side-menu\"/>"
                           "<label class=\"hamb\" for=\"side-menu\"><span class=\"hamb-line\"></span></label>"
                           "<nav class=\"nav\">"
                           "<ul class=\"menu\">"
                           "<li><a href=\"#\">Объекты</a></li>"
                           "<li><a href=\"#\">Добавить</a></li>"
                           "<li><a href=\"#\">Архивы</a></li>"
                           "</ul>"
                           "</nav>"
                           "</header>"
                           "<main>"
                           "<div class=\"objects1\" id=\"obj_id1\">"
                           "<h1>Объект 1</h1>"
                           "<p>Адресс: г. Иваново, ул Харинка, дом 11</p>"
                           "<h2>Сводка на 04.10.2024</h2>"
                           "<p>tпр = 100℃ tоб = 80℃<br>Q = 1200 гкал m = 232234 т</p>"
                           "<button class=\"btn-obj\" id=\"btn_load\">Снять показания</button>"
                           "<button class=\"btn-obj2\" id=\"btn_one\">Выключить</button>"
                           "</div>"
                           "<div id=\"data\">"
                           "<table class=\"table\">"
                           "<thead>"
                           "<tr>"
                           "<th>Дата</th>"
                           "<th>Температура (˚C)</th>"
                           "<th>Объем (м^3)</th>"
                           "<th>Масса (т)</th>"
                           "<th>Давление (МПА)</th>"
                           "<th>ТЭ (ГКал)</th>"
                           "<th>Время работы (ч)</th>"
                           "<th>Ошибки</th>"
                           "</tr>"
                           "</thead>"
                           "<tbody>"
                           "<tr>"
                           "<td>01.11.2024</td>"
                           "<td>T1 = 50,13; T2 = 45,17</td>"
                           "<td>V1 = 1070,052; V2 = 1074,297</td>"
                           "<td>M1 = 1057,311; M2 = 1063,796</td>"
                           "<td>P1 = 0,40; P2 = 0,32;</td>"
                           "<td>Q = 4,988</td>"
                           "<td>24.00</td>"
                           "<td>-</td>"
                           "</tr>"
                           "</tbody>"
                           "</table>"
                           "</div>"
                           "</main>"
                           "<script>"
                           "  document.getElementById('btn_one').addEventListener('click', function () {"
                           "  let request = new XMLHttpRequest();"
                           "  this.textContent = this.textContent === 'Выключить' ? 'Включить' : 'Выключить';"
                           "  if (this.textContent == 'Включить') {"
                           "   this.classList.add(\"active\");"
                           "   document.getElementById('obj_id1').classList.add(\"active_bg\");"
                           "   request.open('GET', '/off', false);"
                           "   request.send();"
                           "  } else if (this.textContent == 'Выключить') {"
                           "   request.open('GET', '/on', false);"
                           "   request.send();"
                           "   this.classList.remove(\"active\");"
                           "   document.getElementById('obj_id1').classList.remove(\"active_bg\");"
                           " }"
                           " });"
                           " document.getElementById('btn_load').addEventListener('click', function () {"
                           "  if (document.getElementById('data').style.display !== \"block\") {"
                           " document.getElementById('data').style.display = \"block\";"
                           "} else {"
                           " document.getElementById('data').style.display = \"none\";"
                           " }"
                           "});"
                           "</script>"
                           "</body>"
                           "<style>"
                           ":root {"
                           "   --white: #f9f9f9;"
                           "   --black: #2149d8;"
                           "   --gray: #b9b9b9;"
                           "}"
                           "* {"
                           "  margin: 0;"
                           "  padding: 0;"
                           "  box-sizing: border-box;"
                           "}"
                           "body {"
                           "  background-color: var(--white);"
                           "  font-family: \"Poppins\", sans-serif;"
                           "}"
                           "a {"
                           "  text-decoration: none;"
                           "}"
                           "ul {"
                           "  list-style: none;"
                           "}"
                           ".header {"
                           "  background-color: var(--black);"
                           "  box-shadow: 1px 1px 5px 0px var(--gray);"
                           "  position: sticky;"
                           "  top: 0;"
                           "  width: 100%;"
                           "  }"
                           ".logo {"
                           "  display: inline-block;"
                           "  color: var(--white);"
                           "  font-size: 40px;"
                           "  margin-left: 10px;"
                           "  height: 90px;"
                           "}"
                           ".nav {"
                           "  width: 100%;"
                           "  height: 100%;"
                           "  position: fixed;"
                           "  background-color: var(--black);"
                           "  overflow: hidden;"
                           "}"
                           ".menu a {"
                           "  display: block;"
                           "  padding: 30px;"
                           "  color: var(--white);"
                           "}"
                           ".menu a:hover {"
                           "   background-color: var(--gray);"
                           "}"
                           ".nav {"
                           "   max-height: 0;"
                           "   transition: max-height .5s ease-out;"
                           "}"
                           ".hamb {"
                           "  cursor: pointer;"
                           "  float: right;"
                           "  padding: 40px 20px;"
                           "}"
                           ".hamb-line {"
                           "  background: var(--white);"
                           "  display: block;"
                           "  height: 2px;"
                           "  position: relative;"
                           "  width: 24px;"
                           "}"
                           ".hamb-line::before,"
                           ".hamb-line::after {"
                           "  background: var(--white);"
                           "  content: '';"
                           "  display: block;"
                           "  height: 100%;"
                           "  position: absolute;"
                           "  transition: all .2s ease-out;"
                           "  width: 100%;"
                           "}"
                           ".hamb-line::before {"
                           "  top: 5px;"
                           "}"
                           ".hamb-line::after {"
                           "  top: -5px;"
                           "}"
                           ".side-menu {"
                           "  display: none;"
                           "}"
                           ".side-menu:checked~nav {"
                           "  max-height: 100%;"
                           "}"
                           ".side-menu:checked~.hamb .hamb-line {"
                           "  background: transparent;"
                           "}"
                           ".side-menu:checked~.hamb .hamb-line::before {"
                           "  transform: rotate(-45deg);"
                           "  top: 0;"
                           "}"
                           "side-menu:checked~.hamb .hamb-line::after {"
                           "  transform: rotate(45deg);"
                           "  top: 0;"
                           "}"
                           "@media (min-width: 900px) {"
                           " .nav {"
                           "   max-height: none;"
                           "   top: 0;"
                           "   position: relative;"
                           "   float: right;"
                           "   width: fit-content;"
                           "  }"
                           " .menu li {"
                           "   float: left;"
                           "  }"
                           "  .menu a:hover {"
                           "   background-color: transparent;"
                           "   color: var(--gray);"
                           "  }"
                           "  .hamb {"
                           "   display: none;"
                           "  }"
                           "}"
                           ".objects1 {"
                           "  text-align: center;"
                           "  background-color: rgb(165, 243, 217);"
                           "  margin-left: 10%;"
                           "  margin-right: 10%;"
                           "  margin-top: 5%;"
                           "  height: 260px;"
                           "}"
                           ".btn-obj {"
                           "   margin-top: 20px;"
                           "   font-weight: 700;"
                           "   color: white;"
                           "   text-decoration: none;"
                           "   padding: .8em 1em calc(.8em + 3px);"
                           "   border-radius: 3px;"
                           "   background: rgb(49, 111, 245);"
                           "   box-shadow: 0 -3px rgb(49, 111, 245) inset;"
                           "   transition: 0.2s;"
                           "}"
                           ".btn-obj:hover {"
                           "   background: rgb(29, 74, 170);"
                           "}"
                           ".btn-obj:active {"
                           "   background: rgb(41, 95, 211);"
                           "   box-shadow: 0 3px rgb(36, 82, 184) inset;"
                           "}"
                           ".btn-obj2 {"
                           "   margin-top: 20px;"
                           "   font-weight: 700;"
                           "   color: white;"
                           "   text-decoration: none;"
                           "   padding: .8em 1em calc(.8em + 3px);"
                           "   border-radius: 3px;"
                           "   background: rgb(33, 185, 147);"
                           "   box-shadow: 0 -3px rgb(33, 185, 147) inset;"
                           "   transition: 0.2s;"
                           "}"
                           ".active {"
                           "   background: rgb(241, 46, 79);"
                           "   box-shadow: 0 3px rgb(145, 25, 51) inset;"
                           "}"
                           ".active_bg {"
                           "   background-color: rgb(216, 83, 83);"
                           "}"
                           ".table {"
                           "   width: 100%;"
                           "   margin-bottom: 20px;"
                           "   border: 1px solid #dddddd;"
                           "   border-collapse: collapse;"
                           "   margin-top: 4%;"
                           "}"
                           ".table th {"
                           "  font-weight: bold;"
                           "  padding: 5px;"
                           "  background: #efefef;"
                           "  border: 1px solid #dddddd;"
                           "}"
                           ".table td {"
                           "  border: 1px solid #dddddd;"
                           "  padding: 5px;"
                           "}"
                           "#data {"
                           " display: none;"
                           "}"
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           ""
                           "</style>"
                           "</html> ";

void setup() {
  Serial.begin(9600);                                             //Открыть последовательное соединение
  WiFi.begin(ssid, password);
  
  pinMode(TXD, OUTPUT);
  pinMode(13, OUTPUT);   
  

  while (--tries && WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  if (WiFi.status() != WL_CONNECTED)
  {
    Serial.println("Non Connecting to WiFi..");
  }
  else
  {
    // Иначе удалось подключиться отправляем сообщение
    // о подключении и выводим адрес IP
    Serial.println("");
    Serial.println("WiFi connected");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
  }

  delay(500);
  Serial.println("Waiting to connect…");

  server.on("/", []() {                     //Определите функцию обработки корневого пути (HTML-сообщение)
    server.send(200, "text/html", htmlMessage);
  });

  server.on("/off", off_modules);               //Определите функцию обработки корневого пути (HTML-сообщение)
  server.on("/on", on_modules);               //Определите функцию обработки корневого пути (HTML-сообщение)

  server.begin(); //Start the server
  Serial.println("Server listening");
}

void loop() {
  server.handleClient(); //Обработка входящих запросов
}

void off_modules() {
  digitalWrite(TXD, HIGH);
  Serial.println("Status: Off");
  server.send(200, "text/html", htmlMessage); 
}

void on_modules() {
  digitalWrite(TXD, LOW);
  Serial.println("Status: On");
  server.send(200, "text/html", htmlMessage); 
}
